### ISSUE TITLE
Needs dependency on lxterminal

### ISSUE THREAD

**Issue by cameroncc** [cdeccio/cougarnet#1]
In README.md it says it depends on `lxde-terminal`, but the correct package name on Debian 11 is `lxterminal`. The example wasn't working for me until I installed that package but it works fine after. I think it would also be good to add `lxterminal` as one of the packages to install in `cdeccio/byu-cs460-f2021/hw-link-layer/README.md`

Here's my terminal output:
```zsh
cameron@cs460:~/cougarnet-example
$ cougarnet simple-net.cfg 
rm: cannot remove '/run/netns/h2': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/cougarnet", line 4, in <module>
    __import__('pkg_resources').run_script('cougarnet==0.0.0', 'cougarnet')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/cougarnet-0.0.0-py3.9.egg/EGG-INFO/scripts/cougarnet", line 5, in <module>
  File "/usr/local/lib/python3.9/dist-packages/cougarnet-0.0.0-py3.9.egg/cougarnet/virtualnet.py", line 740, in main
  File "/usr/local/lib/python3.9/dist-packages/cougarnet-0.0.0-py3.9.egg/cougarnet/virtualnet.py", line 589, in start
  File "/usr/local/lib/python3.9/dist-packages/cougarnet-0.0.0-py3.9.egg/cougarnet/virtualnet.py", line 177, in start
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lxterminal'
cameron@cs460:~/cougarnet-example
$ sudo apt install lxterminal
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  lxterminal
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 95.6 kB of archives.
After this operation, 604 kB of additional disk space will be used.
Get:1 http://192.168.23.122/debian bullseye/main amd64 lxterminal amd64 0.4.0-1 [95.6 kB]
Fetched 95.6 kB in 0s (8,496 kB/s)
Selecting previously unselected package lxterminal.
(Reading database ... 168449 files and directories currently installed.)
Preparing to unpack .../lxterminal_0.4.0-1_amd64.deb ...
Unpacking lxterminal (0.4.0-1) ...
Setting up lxterminal (0.4.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for mailcap (3.69) ...
Scanning processes...                                                           
Scanning linux images...                                                        

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.
cameron@cs460:~/cougarnet-example
$ cougarnet simple-net.cfg   
Ctrl-c to quit
```

**Comment by cdeccio** [comment]
Fixed with #2
